### ISSUE TITLE
Intellij crashes when restarts after pluing install

### ISSUE THREAD

**Issue by marcioamatte** [redhat-developer/intellij-dependency-analytics#146]
Hello,

I installed the plugin and after restarting the IDE I received this exception:

```
java.lang.NoSuchMethodError: 'com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$Message com.redhat.devtools.intellij.telemetry.core.service.TelemetryMessageBuilder$ActionMessage.property(java.lang.String, java.lang.String)'
	at org.jboss.tools.intellij.exhort.ApiService.getComponentAnalysis(ApiService.java:82)
	at org.jboss.tools.intellij.componentanalysis.CAService.performAnalysis(CAService.java:64)
	at org.jboss.tools.intellij.componentanalysis.CAAnnotator.lambda$doAnnotate$1(CAAnnotator.java:62)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

To reproduce:

OS: Debian Linux 12
Java Version: Amazon Corretto 21 - amd64 (OpenJDK)
Maven Version: 3.9.0
Intellij Version: Ultimate 2023.3

**Comment by zvigrinberg** [comment]
Hi @marcioamatte ,
This Bug was already fixed , will be part of the forthcoming release
